//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UndertaleBattleSystemPrototype.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UndertaleBattleSystemPrototype.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap actButton {
            get {
                object obj = ResourceManager.GetObject("actButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap actButtonBlank {
            get {
                object obj = ResourceManager.GetObject("actButtonBlank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap appartement1 {
            get {
                object obj = ResourceManager.GetObject("appartement1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap appartement2 {
            get {
                object obj = ResourceManager.GetObject("appartement2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arlos {
            get {
                object obj = ResourceManager.GetObject("arlos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap attackFistD {
            get {
                object obj = ResourceManager.GetObject("attackFistD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap attackFistL {
            get {
                object obj = ResourceManager.GetObject("attackFistL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap attackHoof {
            get {
                object obj = ResourceManager.GetObject("attackHoof", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap attackHorn {
            get {
                object obj = ResourceManager.GetObject("attackHorn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap attackHornO {
            get {
                object obj = ResourceManager.GetObject("attackHornO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap attackLeaves {
            get {
                object obj = ResourceManager.GetObject("attackLeaves", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap attackLeavesO {
            get {
                object obj = ResourceManager.GetObject("attackLeavesO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bookshelfB {
            get {
                object obj = ResourceManager.GetObject("bookshelfB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bookshelfG {
            get {
                object obj = ResourceManager.GetObject("bookshelfG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bookshelfR {
            get {
                object obj = ResourceManager.GetObject("bookshelfR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bookshelfY {
            get {
                object obj = ResourceManager.GetObject("bookshelfY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bush {
            get {
                object obj = ResourceManager.GetObject("bush", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Enemy&gt;
        ///  &lt;Stats hp =&quot;80&quot;
        ///         atk =&quot;4&quot;
        ///         gold =&quot;50&quot;&gt;
        ///  &lt;/Stats&gt;
        ///  &lt;Attacks&gt;
        ///    &lt;Attack name =&quot;LeafAttack&quot;
        ///            value =&quot;0&quot;&gt;
        ///    &lt;/Attack&gt;
        ///    &lt;Attack name =&quot;FistAttack&quot;
        ///            value =&quot;1&quot;&gt;
        ///    &lt;/Attack&gt;
        ///  &lt;/Attacks&gt;
        ///  &lt;Dialog&gt;
        ///    &lt;Text string =&quot;...Do what you will Nori. But please be careful.&quot;&gt;&lt;/Text&gt;
        ///    &lt;Text string =&quot;Franky and his gang broke my antler off a week ago...&quot;&gt;&lt;/Text&gt;
        ///    &lt;Text string =&quot;Yeah...&quot;&gt;&lt;/Text&gt;
        ///    &lt;Text  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Calum {
            get {
                return ResourceManager.GetString("Calum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Calum_FS {
            get {
                object obj = ResourceManager.GetObject("Calum_FS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Calum_WS {
            get {
                object obj = ResourceManager.GetObject("Calum_WS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap controlsSprite {
            get {
                object obj = ResourceManager.GetObject("controlsSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DialogFont {
            get {
                object obj = ResourceManager.GetObject("DialogFont", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Donna {
            get {
                object obj = ResourceManager.GetObject("Donna", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fightButton {
            get {
                object obj = ResourceManager.GetObject("fightButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fightButtonBlank {
            get {
                object obj = ResourceManager.GetObject("fightButtonBlank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fightUISprite {
            get {
                object obj = ResourceManager.GetObject("fightUISprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Enemy&gt;
        ///  &lt;Stats hp =&quot;100&quot;
        ///         atk =&quot;5&quot;
        ///         gold =&quot;200&quot;&gt;
        ///  &lt;/Stats&gt;
        ///  &lt;Attacks&gt;
        ///    &lt;Attack name =&quot;HornAttack&quot;
        ///            value =&quot;0&quot;&gt;
        ///    &lt;/Attack&gt;
        ///    &lt;Attack name =&quot;HoofAttack&quot;
        ///            value =&quot;1&quot;&gt;
        ///    &lt;/Attack&gt;
        ///  &lt;/Attacks&gt;
        ///  &lt;Dialog&gt;
        ///    &lt;Text string =&quot;Ugh fine. I guess I can do that... not that he needs it.&quot;&gt;&lt;/Text&gt;
        ///    &lt;Text string =&quot;Because he&apos;s weak. People like him don&apos;t survive society. He&apos;s a loser.&quot;&gt;&lt;/Text&gt;
        ///    &lt;Text string =&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Franky {
            get {
                return ResourceManager.GetString("Franky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Franky_FS {
            get {
                object obj = ResourceManager.GetObject("Franky_FS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Franky_WS {
            get {
                object obj = ResourceManager.GetObject("Franky_WS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gameOverSprite {
            get {
                object obj = ResourceManager.GetObject("gameOverSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap heart {
            get {
                object obj = ResourceManager.GetObject("heart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap itemButton {
            get {
                object obj = ResourceManager.GetObject("itemButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap itemButtonBlank {
            get {
                object obj = ResourceManager.GetObject("itemButtonBlank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap library {
            get {
                object obj = ResourceManager.GetObject("library", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap libraryDoor {
            get {
                object obj = ResourceManager.GetObject("libraryDoor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mercyButton {
            get {
                object obj = ResourceManager.GetObject("mercyButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mercyButtonBlank {
            get {
                object obj = ResourceManager.GetObject("mercyButtonBlank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mercyButtonSpare {
            get {
                object obj = ResourceManager.GetObject("mercyButtonSpare", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mercyButtonSpareBlank {
            get {
                object obj = ResourceManager.GetObject("mercyButtonSpareBlank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap noriB1 {
            get {
                object obj = ResourceManager.GetObject("noriB1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap noriB2 {
            get {
                object obj = ResourceManager.GetObject("noriB2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap noriBR {
            get {
                object obj = ResourceManager.GetObject("noriBR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap noriF1 {
            get {
                object obj = ResourceManager.GetObject("noriF1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap noriF2 {
            get {
                object obj = ResourceManager.GetObject("noriF2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap noriFR {
            get {
                object obj = ResourceManager.GetObject("noriFR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap noriL1 {
            get {
                object obj = ResourceManager.GetObject("noriL1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap noriL2 {
            get {
                object obj = ResourceManager.GetObject("noriL2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap noriLR {
            get {
                object obj = ResourceManager.GetObject("noriLR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap noriR1 {
            get {
                object obj = ResourceManager.GetObject("noriR1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap noriR2 {
            get {
                object obj = ResourceManager.GetObject("noriR2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap noriRR {
            get {
                object obj = ResourceManager.GetObject("noriRR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PauseFormBackground {
            get {
                object obj = ResourceManager.GetObject("PauseFormBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Player&gt;
        ///  &lt;Stats&gt;
        ///    &lt;General gold =&quot;0&quot;&gt;&lt;/General&gt;
        ///    &lt;Battle currentHP =&quot;40&quot;
        ///            atk =&quot;5&quot;&gt;
        ///    &lt;/Battle&gt;
        ///  &lt;/Stats&gt;
        ///  &lt;Items&gt;
        ///    &lt;Inventory&gt;
        ///      &lt;Item name =&quot;Test Item 1&quot;
        ///            heal =&quot;10&quot;&gt;
        ///      &lt;/Item&gt;
        ///      &lt;Item name =&quot;Test Item 2&quot;
        ///            heal =&quot;5&quot;&gt;
        ///      &lt;/Item&gt;
        ///      &lt;Item name =&quot;Test Item 3&quot;
        ///            heal =&quot;20&quot;&gt;
        ///      &lt;/Item&gt;
        ///      &lt;Item name =&quot; &quot;
        ///            heal =&quot;0&quot;&gt;
        ///      &lt;/Item&gt;
        ///    &lt;/Inventory&gt;
        ///  &lt;/Items&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap road2 {
            get {
                object obj = ResourceManager.GetObject("road2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap roadTurn {
            get {
                object obj = ResourceManager.GetObject("roadTurn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sharol_WS {
            get {
                object obj = ResourceManager.GetObject("Sharol_WS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShopFormBackground {
            get {
                object obj = ResourceManager.GetObject("ShopFormBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Enemy&gt;
        ///  &lt;Stats hp =&quot;100&quot;
        ///         atk =&quot;5&quot;&gt;
        ///  &lt;/Stats&gt;
        ///  &lt;Attacks&gt;
        ///    &lt;Attack name =&quot;LeafAttack&quot;
        ///            value =&quot;0&quot;&gt;
        ///    &lt;/Attack&gt;
        ///    &lt;Attack name =&quot;LeafAttack&quot;
        ///            value =&quot;1&quot;&gt;
        ///    &lt;/Attack&gt;
        ///  &lt;/Attacks&gt;
        ///  &lt;ActMenu&gt;
        ///    &lt;Act spareValue =&quot;-1&quot;
        ///          actName =&quot;Check&quot;
        ///          actLine1 =&quot;TESTENEMY 2 ATK 0 DEF&quot;
        ///          actLine2 =&quot;Basic enemy example&quot;&gt;
        ///    &lt;/Act&gt;
        ///    &lt;Act spareValue =&quot;1&quot;
        ///          actName =&quot;Joke&quot;
        ///          actLine1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestEnemy {
            get {
                return ResourceManager.GetString("TestEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Dialogue&gt;
        ///  &lt;text value =&quot;This door is locked.&quot;&gt;&lt;/text&gt;
        ///  &lt;text value =&quot;...A small dog?&quot;&gt;&lt;/text&gt;
        ///  &lt;text value =&quot;No answer.&quot;&gt;&lt;/text&gt;
        ///  &lt;text value =&quot;There&apos;s a frat party going on but you&apos;re just a kid. No party for you.&quot;&gt;&lt;/text&gt;
        ///  &lt;text value =&quot;Hey there... New face in town, eh? I&apos;m Sharol, nice to meetcha. Got any spare change?&quot;&gt;&lt;/text&gt;
        ///  &lt;text value =&quot;Well if you don&apos;t got any that&apos;s okay. Just be careful passing through town now. Franky and his bison gang ar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap titleSprite {
            get {
                object obj = ResourceManager.GetObject("titleSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
